### ISSUE TITLE
Round tripping Illumina FASTQ file converts quality score # to !

### ISSUE THREAD

**Issue by Midnighter** [jkbonfield/fqzcomp#5]
I'm using `fqz_comp` from bioconda:

```
fqzcomp                   4.6                  hd03093a_3    bioconda
```

I compress one of my FASTQ files with (I believe it also happens with different settings)

```
fqz_comp -n2 -s7+ -e -b -q3 -P sample.fastq sample.fqz
```

then I decompress and compare the output:

```
fqz_comp -d sample.fqz sample.fastq2
md5sum sample.fastq sample.fastq2  # they differ
diff sample.fastq sample.fastq2
```

As far as I can tell the diff shows that all quality scores containing `#` have been changed to `!`. Maybe there are further differences.

**Comment by jkbonfield** [comment]
This is one of the limitations of fqzcomp.  "N" bases are encoded as zero-confidence, so they can then be replaced by other base types, giving us just 4 DNA symbols to encode.  This works well as a compression strategy, but it relies on a sane input file!

It was true when fqzcomp was written (I think) that quality 0 implied N, but oddly no more.  It makes no sense as in the Phred quality scale a 0 means 100% chance of being wrong.  If you call an A with quality 0 then you're really saying "pick anything other than A because I'm dead certain it's not actually A!".    The  minimal workaround for this defect however was to spot this problem occurring and by changing quality 0 on non-N bases to quality 1, so zero could once again be retained purely for N.

This isn't something I'm likely to fix.

I started again with a more modern fqzcomp (https://github.com/jkbonfield/fqzcomp5/).  That's still very much alpha quality and it's a bit of a background project so may not get updated quickly.  You also shouldn't rely on the file format not changing.  Infact it'll almost certainly change before I make the first official release.  However if you're curious to benchmark something then give it a whirl.  I'd be interested in any feedback.  Fqzcomp5 may not always give as good a ratio (but sometimes much better also) as it's block based, with a longer term aim to permit coarse random access capabilities.

**Comment by Midnighter** [comment]
Thank you for the quick response and the pointer to the new project. Your argument makes sense but I'm looking for a good format to archive my FASTQ sequences. So I care a lot about compression ratio but also want to faithfully maintain the data.
